#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname ${0}`/bigtop.bom

bom2props() {
cat <<__EOT__ 
hbase.version=$HBASE_VERSION
zookeeper.version=$ZOOKEEPER_VERSION
hadoop.version=$HADOOP_VERSION
hadoop.security.version=$HADOOP_VERSION
hadoop-0.23.version=$HADOOP_VERSION
__EOT__
}

bom2props >> src/ivy/libraries.properties
bom2props >> src/build.properties 

# The following is a workaround for Hadoop 0.23 layout
cat >> src/build.properties << __EOT__
hadoop.mapreduce.jar=\${hadoop.root}/share/hadoop/mapreduce/hadoop-mapreduce-client-core-\${hadoop.version.ant-internal}.jar
hadoop.mapreduce.test.jar=\${hadoop.root}/share/hadoop/mapreduce/hadoop-mapreduce-test-\${hadoop.version.ant-internal}.jar
hadoop.mapreduce.tools.jar=\${hadoop.root}/share/hadoop/mapreduce/hadoop-mapreduce-tools-\${hadoop.version.ant-internal}.jar
__EOT__

# Workaround because renamed o.a.h.h.serde.Constants to o.a.h.h.serde.serdeConstants in a non-backwards compatible way in 0.10.0
# This is being fixed via HIVE-4001. Please remove this workaround once that gets into a release (Hive 0.11?)
mkdir -p src/serde/src/java/org/apache/hadoop/hive/serde
cat << '__EOT__' > src/serde/src/java/org/apache/hadoop/hive/serde/Constants.java
package org.apache.hadoop.hive.serde;

/**
 * For backward compatibility
 */
@Deprecated
public class Constants extends serdeConstants {
}
__EOT__

ant -f src/build.xml `bom2props | sed -e 's#^#-D#'`  -Dhadoop.security.version.prefix=0.23 package "$@"
